---
- name: Ensure httpd is installed
  yum:
    name: httpd
    state: present
  become: yes
- name: Ensure directory for content exists
  file:
    path: /var/www/html/repos/centos
    state: directory
  become: yes
- name: Ensure firewall permits web traffic
  firewalld:
    service: http
    zone: public
    state: enabled
    immediate: yes
    permanent: yes
  become: yes
- name: Ensure web service is started and enabled at boot
  systemd:
    name: httpd
    state: started
    enabled: yes
  become: yes
