---
- name: Ensure key for chef RPMs is installed
  rpm_key:
    key: https://packages.chef.io/chef.asc
    state: present
- name: Ensure chef-stable repo has been added
  yum_repository:
    name: chef-stable
    description: Chef stable repository - https://docs.chef.io/packages.html
    baseurl: https://packages.chef.io/repos/yum/stable/el/7/x86_64/
    gpgcheck=1
    enabled=1
  become: yes
- name: Ensure localpkgs repo has been added
  yum_repository:
    name: localpkgs
    description: Repository for custom site packages
    baseurl: http://10.1.1.254/centos/$releasever/localpkgs/$basearch/
  become: yes
# - name: Get status of repo files
#   stat:
#     path: /etc/yum.repos.d/CentOS-Base.repo
#   register: base_repo
#   failed_when: false
# - name: Ensure default repositories are disabled but saved
#   command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.orig
#   become: yes
#   when: base_repo.stat.exists
# - name: Ensure local repo mirror is enabled
#   copy:
#     dest: /etc/yum.repos.d/local.repo
#     src: local.repo
#   become: yes
