---
- Ensure localpkgs repo has been added
  yum_repository:
    name: localpkgs
    description: Repository for custom site packages
    baseurl: http://10.1.1.254/centos/$releasever/localpkgs/$basearch/
  become: yes
# - name: Get status of repo files
#   stat:
#     path: /etc/yum.repos.d/CentOS-Base.repo
#   register: base_repo
#   failed_when: false
# - name: Ensure default repositories are disabled but saved
#   command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.orig
#   become: yes
#   when: base_repo.stat.exists
# - name: Ensure local repo mirror is enabled
#   copy:
#     dest: /etc/yum.repos.d/local.repo
#     src: local.repo
#   become: yes
