---
- name: Ensure service configuration files are up to date
  copy:
    dest: "/etc/named.conf"
    src: "{{ item }}"
  with_items:
    - named.conf
  become: yes
- name: Ensure zone files are up to date
  copy:
    dest: "/etc/named/{{ item }}"
    src: "{{ item }}"
  with_items:
    - example.com.zone
    - 1.1.10.in-addr.arpa.zone
  become: yes
