---
- name: Ensure top level directory for content exists
  file:
    path: "{{ docroot }}/centos/{{ release_full }}"
    state: directory
  become: yes
- name: Ensure repo subdirectories exists
  file:
    path: "{{ docroot }}/centos/{{ release_full }}/{{ item }}/x86_64"
    state: directory
  with_items:
    - os
    - isos
    - updates
    - centosplus
    - extras
    - local
  become: yes
- name: Ensure release link exists
  file:
    path: "{{ docroot }}/centos/{{ release_major }}"
    src: "{{ docroot }}/centos/{{ release_full }}"
    state: link
  become: yes
- name: Ensure exclude lists are installed before syncing
  copy:
    dest: "{{ docroot }}/centos/{{ release_full }}/{{ item }}/x86_64/exclude.list"
    src: "{{ item }}.list"
  with_items:
    - os
    - isos
    - updates
    - centosplus
    - extras
  become: yes
# Create localpkgs repo
- name: Ensure directories for building the new ISO image exist
  file:
    path: "{{ localpkgs }}/Packages"
    state: directory
  become: yes
