---
# Create localpkgs repo
- name: Ensure directories for building the new ISO image exist
  file:
    path: "{{ localpkgs }}/Packages"
    state: directory
  become: yes
- name: Ensure the chefdk RPM has been downloaded
  get_url:
    url: "https://packages.chef.io/files/stable/chefdk/1.4.3/el/7/chefdk-1.4.3-1.el7.x86_64.rpm"
    dest: "{{ localpkgs }}/Packages/chefdk-1.4.3-1.el7.x86_64.rpm"
    checksum: "sha256:bb70be05a6a99071d26ec288d338459fe71fdd6ab0e4cbb661ae66dfb6c82fc5"
  become: yes
- name: Ensure the chef-server-core RPM has been downloaded
  get_url:
    url: "https://packages.chef.io/files/stable/chef-server/12.15.8/el/7/chef-server-core-12.15.8-1.el7.x86_64.rpm"
    dest: "{{ localpkgs }}/Packages/chef-server-core-12.15.8-1.el7.x86_64.rpm"
    checksum: "sha256:a39b70bbbc8ba60d54c827d2a002f7b1d4f48629f8316ae59ae21ab2c73396d8"
  become: yes
 - name: Ensure the repodata has been updated
   command: "createrepo ."
   args:
     chdir: "{{ localpkgs }}"
