---
- name: Ensure necessary packages are installed
  yum:
    name: dnsmasq
    state: present
  become: yes
- name: Ensure dnsmasq is configured
  template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.js
    backup: yes
  become: yes
- name: Ensure dnsmasq is enabled
  service:
    name: dnsmasq
    state: started
    enabled: yes
  become: yes
