---
- name: Ensure necessary packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - dnsmasq
    - python-firewall
  become: yes
- name: Ensure dnsmasq is configured
  template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.js
    backup: yes
  become: yes
  notify: restart_dnsmasq
- name: Ensure our own hostname is in the /etc/hosts so dnsmasq can resolve it
  lineinfile:
    path: /etc/hosts
    line: 10.1.1.254 router.example.com router pxeserver.example.com pxeserver repomirror.example.com repomirror
  become: yes
- name: Ensure firewalld and dnsmasq are started and enabled at boot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dnsmasq
    - firewalld
  become: yes
- name: Ensure internal dhcp and dns traffic is allowed
  firewalld:
    service: "{{ item.service }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: "{{ item.zone }}"
  with_items:
    - { zone: internal, service: dhcp }
    - { zone: internal, service: dns }
  become: yes
