---                                                                              
- name: Ensure chefdk package is installed                                  
  yum:                                                                           
    name: chefdk
    state: present                                                               
  become: yes
