---
- name: Ensure tftp is enabled in the xinetd configs
  lineinfile:
    path: /etc/xinetd.d/tftp
    state: present
    regexp: "^(	disable.*=.)yes$"
    line: '\1no'
    backrefs: yes
  become: yes
- name: Ensure xinetd and httpd are started and enabled at boot
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - xinetd
    - httpd
  become: yes
