---
- name: Ensure necessary packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - tftp-server
    - xinetd
    - syslinux
    - httpd
  become: yes
- name: Ensure tftp is enabled in the xinetd configs
  lineinfile:
    path: /etc/xinetd.d/tftp
    state: present
    regexp: "^(	disable.*=.)yes$"
    line: '\1no'
    backrefs: yes
  become: yes
- name: Ensure directories for PXE content exists
  file:
    path: "{{ tftproot }}/pxelinux/pxelinux.cfg"
    state: directory
  become: yes
- name: Ensure the pxelinux NBP and support files are installed
  synchronize:
    dest: "{{ tftproot }}/pxelinux/{{ item }}"
    src: "/usr/share/syslinux/{{ item }}"
  with_items:
    - pxelinux.0
    - menu.c32
  become: yes
- name: Ensure the default config and support files for pxelinux are installed
  synchronize:
    dest: "{{ tftproot }}/pxelinux/pxelinux.cfg/{{ item }}"
    src: "{{ item }}"
  with_items:
    - default
    - graphics.conf
  become: yes
- name: Ensure the kernel and initrd.img launched by pxelinux exist
  synchronize:
    dest: "{{ tftproot }}/pxelinux/{{ item }}"
    src: "{{ rsync_mirror }}/{{ release_full }}/os/x86_64/isolinux/{{ item }}"
  with_items:
    - vmlinuz
    - initrd.img
  become: yes
- name: Ensure directory for kickstart files exists
  file:
    path: "{{ docroot }}/ks"
    state: directory
  become: yes
- name: Ensure kickstart files are copy to the ks web directory
  synchronize:
    dest: "{{ docroot }}/ks/{{ item }}"
    src: "{{ workspace }}/files/{{ item }}"
  with_items:
    - ks.cfg
    - workstation-ks.cfg
  become: yes
- name: Ensure xinetd and httpd are started and enabled at boot
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - xientd
    - httpd
  become: yes
- name: Ensure firewall permits tftp and http traffic
  firewalld:
    service: "{{ item }}"
    zone: public
    state: enabled
    immediate: yes
    permanent: yes
  with_items:
    - tftp
    - httpd
  become: yes
