---
#- hosts: all
#  roles:
#    - role: use-local-repo

- hosts:
    - router.example.com
  roles:
    - role: natgw
    - role: dnsmasq
    - role: repomirror
    - role: pxeserver

- hosts:
    - chefserver.example.com
  roles:
    - role: chefserver

- hosts:
    - buildbox.example.com
  roles:
    - role: chefworkstation
