---
- hosts: all
  roles:
    - role: use-local-repo
- hosts: repomirror
  roles:
    - role: repomirror
- hosts: chefserver
  roles:
    - role: chefserver
- hosts: chefworkstation
  roles:
    - role: chefworkstation
