---
- hosts: all
  roles:
    - role: use-local-repo
- hosts:
    - router.example.com
  roles:
    - { role: natgw, tags: natgw }
    - { role: dnsmasq, tags: dnsmasq }
    - { role: repomirror, tags: repomirror }
    - { role: pxeserver, tags: pxeserver }
    - { role: gitserver, tags: gitserver }

- hosts:
    - chefserver.example.com
  roles:
    - { role: chefserver, tags: chefserver }

- hosts:
    - chefworkstation.example.com
  roles:
    - { role: chefworkstation, tags: chefworkstation }
