---
- hosts: all
  roles:
    - { role: all-pre-configuration, tags: all-pre-configuration }

- hosts: router
  roles:
    - { role: natgw, tags: natgw }
    - { role: dnsmasq, tags: dnsmasq }
    - { role: pxeserver, tags: pxeserver }
    - { role: gitserver, tags: gitserver }

- hosts: repomirror
  roles:
    - { role: repomirror, tags: repomirror }

- hosts: chefserver
  roles:
    - { role: chefserver, tags: chefserver }

- hosts: chefworkstation
  roles:
    - { role: chefworkstation, tags: chefworkstation }

- hosts: bind
  roles:
    - { role: bind, tags: bind }

- hosts: isc-dhcp
  roles:
    - { role: isc-dhcp, tags: isc-dhcp }

- hosts: all
  roles:
    - role: use-local-repo

