---
- hosts: all
  roles:
    - role: use-local-repo
- hosts: natgw
  roles:
    - role: natgw
- hosts: dnsmasq 
  roles:
    - role: dnsmasq
- hosts: repomirror
  roles:
    - role: repomirror
- hosts: pxeserver
  roles:
    - role: pxeserver
- hosts: chefserver
  roles:
    - role: chefserver
- hosts: chefworkstation
  roles:
    - role: chefworkstation
