---
- name: Ensure the dhcpd configuration is up to date
  copy:
    dest: "/etc/dhcp/{{ item }}"
    src: "{{ item }}"
  with_items:
    - dhcpd.conf
    - dhcpd.master
    - dhcpd.failover-primary
    - dhcpd.failover-secondary
  become: yes
  notify: restart_dhcpd
